### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by 3341232786** [rickyhoho/simple_test#1]
> !!test
[MCDR] [16:31:42] [testing/INFO]: [simple_test] 你的权限等级是[server]
Exception in thread testing:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.r
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.n
    self._target(*self._args, **self._kwargs)
  File "D:\WwwServer1.20.1\server\Survival\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "D:\WwwServer1.20.1\server\Survival\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins\[自检]simple_test-3.0.0.mcdr\simple_test\__init__.py", line 39, in test
  File "plugins\[自检]simple_test-3.0.0.mcdr\simple_test\utils.py", line 26, in get_yaml
  File "C:\Users\sssye\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packad
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "C:\Users\sssye\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packan
    raise AttributeError(s, name=None)
AttributeError:
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "plugins\[自检]simple_test-3.0.0.mcdr\simple_test\utils.py", line 26

        content = yaml.load(y, Loader=yaml.Loader)

**Comment by 3341232786** [comment]
请问应该如何解决呢

**Comment by 3341232786** [comment]
解决了，还是要谢谢

**Comment by Mooling0602** [comment]
> 解决了，还是要谢谢

怎么解决的，我有类似的报错: 
> !!test
[MCDR] [15:22:02] [testing/INFO]: [simple_test] 你的权限等级是[server]
Exception in thread testing:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mooling/.local/share/pipx/venvs/mcdreforged/lib/python3.11/site-packages/mcdreforged/api/decorator/new_thread.py", line 29, in wrapped_target
    raise e from None
  File "/home/mooling/.local/share/pipx/venvs/mcdreforged/lib/python3.11/site-packages/mcdreforged/api/decorator/new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins/simple_test-3.0.0.mcdr/simple_test/__init__.py", line 39, in test
  File "plugins/simple_test-3.0.0.mcdr/simple_test/utils.py", line 26, in get_yaml
  File "/home/mooling/.local/share/pipx/venvs/mcdreforged/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1085, in load
    error_deprecation('load', 'load', arg=_error_dep_arg, comment=_error_dep_comment)
  File "/home/mooling/.local/share/pipx/venvs/mcdreforged/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1039, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"load()" has been removed, use

  yaml = YAML(typ='rt')
  yaml.load(...)

and register any classes that you use, or check the tag attribute on the loaded data,
instead of file "plugins/simple_test-3.0.0.mcdr/simple_test/utils.py", line 26

        content = yaml.load(y, Loader=yaml.Loader)

**Comment by 3341232786** [comment]
我不确定把修改过的内容发出来是否会侵犯原作者的权益

**Comment by Mooling0602** [comment]
> 我不确定把修改过的内容发出来是否会侵犯原作者的权益

应该不会，插件是开源的

**Comment by Dreoka** [comment]
问了一下AI
这样改可以运行
第2行加1行
`from ruamel.yaml import YAML`
第26行把
`content = yaml.load(y, Loader=yaml.Loader)`
改成
```
yaml = YAML(typ='rt')
content = yaml.load(y)
```

**Comment by Dreoka** [comment]
> > 我不确定把修改过的内容发出来是否会侵犯原作者的权益
> 
> 应该不会，插件是开源的

问了一下AI
这样改可以运行
第2行加1行
`from ruamel.yaml import YAML`
第26行把
`content = yaml.load(y, Loader=yaml.Loader)`
改成
```
yaml = YAML(typ='rt')
content = yaml.load(y)
```
